# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-20.04
    env:
      TAG: "${{github.sha}}"
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      NODE_OPTIONS: "--max-old-space-size=4096"
      
    steps:
      - uses: actions/checkout@v2
      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      # install npm deps
      - name: install all packages
        run: npm install

      - name: javascript implementation
        working-directory: ./javascript
        run: |
          npm install
          npm run lint
          npm run build

      - name: javascript tests
        uses: GabrielBB/xvfb-action@v1.4
        with:
          working-directory: ./javascript
          run: npm run test

      - name: examples
        working-directory: ./examples/browser
        run: |
          npm install
          npm run lint
          npm run build
